### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'classes_num'

### ISSUE THREAD

**Issue by ady-yu** [jakeywu/ocr_torch#3]
可以问一下这个报错是为什么吗
Traceback (most recent call last):
  File "train.py", line 236, in <module>
    main(cus_params, cus_logger)
  File "train.py", line 27, in main
    model = build_model(conf["model"])
  File "/root/fish/projects/ocr_torch/nets/__init__.py", line 12, in build_model
    module_class = eval(module_name)(**config)
TypeError: __init__() missing 1 required positional argument: 'classes_num'

**Comment by aibohang** [comment]
我也在文字识别的时候遇到了这个问题，请问您解决了吗
